#!/bin/sh

master_list=$( for i in $( find /export/master/ -maxdepth 1 -type d 2>/dev/null ); do
	p1=${i%%/export/master/*}
	p2=${i##*/export/master/}
	[ -z "${p2}" ] && continue
	printf "${p2} "
done )

[ -z "${master_list}" ] && exit 0

master_ips=$( for i in ${master_list}; do
	[ ! -r /export/master/${i}/ip ] && continue
	master_num=$(( master_num + 1 ))
	ip=$( cat /export/master/${i}/ip )
	[ -z "${ip}" ] && continue
	master_num=$(( master_num + 1 ))
	printf "${ip} "
done )

[ -z "${master_ips}" ] && exit 0

master_num=$( echo ${master_ips} | wc -w | awk '{printf $1}' )

[ -z "${master_num}" ] && exit 0

echo "k8s_master_num=\"${master_num}\""
echo "k8s_master_list=\"${master_list}\""
echo "k8s_master_ips=\"${master_ips}\""

exit 0
