apiVersion: v1
kind: Service
metadata:
  namespace: efk-logging
  name: elasticsearch-logging
  labels:
    component: elasticsearch
    #role: master
    role: client
spec:
  #type: LoadBalancer
  selector:
    component: elasticsearch
    #role: master
    role: client
  ports:
  - name: http
    port: 9200
    protocol: TCP
